techsalad:
  waitDuration: 2s

resilience4j:
  timelimiter:
    instances:
        getSalads:
          timeoutDuration: 1100ms
          cancelRunningFuture: false

management:
  endpoints:
    web:
      exposure:
        include: "timelimiters,timelimiterevents"
