resilience4j:

  # https://resilience4j.readme.io/docs/bulkhead#create-and-configure-a-bulkhead
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 2
        maxWaitDuration: 30s
    instances:
      salads:
        baseConfig: default
      drinks:
        maxWaitDuration: 30s
        maxConcurrentCalls: 2

  # https://resilience4j.readme.io/docs/bulkhead#create-and-configure-a-threadpoolbulkhead
  thread-pool-bulkhead:
    configs:
      default:
        maxThreadPoolSize: 2
        coreThreadPoolSize: 1
        queueCapacity: 2
    instances:
      salads:
        baseConfig: default
      drinks:
        baseConfig: default

drinks:
  url: http://localhost:8080/drinks

salads:
  url: http://localhost:8080/salads